### ISSUE TITLE
Logo stretches on mobile

### ISSUE THREAD

**Issue by ahnl** [Testausserveri/qrpyora#13]
![6B8B5230-66EE-46DC-86DD-4E1BD4CB9D42](https://user-images.githubusercontent.com/46541386/128754693-c23c15f4-ff79-4b39-98ec-fa526c0ed705.png)

Lol.

**Comment by developerfromjokela** [comment]
Bruh

**Comment by kymppi** [comment]
Normal for me![Screenshot_20210809_212239_com.android.chrome.jpg](https://user-images.githubusercontent.com/48528700/128755010-ba7f8635-56aa-4a9b-b2de-df3678aee405.jpg)

**Comment by developerfromjokela** [comment]
iPhone users: @ahnl

**Comment by Trimpsuz** [comment]
kokeile kovempaa

**Comment by ahnl** [comment]
Probably just a Safari bug then.

**Comment by developerfromjokela** [comment]
Yes
