### ISSUE TITLE
Webhook should contain the name and location of the bike

### ISSUE THREAD

**Issue by ahnl** [Testausserveri/qrpyora#17]
![image](https://user-images.githubusercontent.com/46541386/129327687-e6c48751-485c-4adc-8de5-678929d60c2c.png)

Should be able to tell what bike is the photo originating from.

**Comment by developerfromjokela** [comment]
Good idea. Should be an easy fix. One line basically

**Comment by developerfromjokela** [comment]
Commit https://github.com/Testausserveri/qrpyora/commit/00e8a4740b605dcd8dc6b87bd07095136e0cc32f should resolve this issue.

**Comment by developerfromjokela** [comment]
![image](https://user-images.githubusercontent.com/40487414/129573510-d3228d04-f4a7-4749-a843-0e0829d0a5a8.png)
